export default [
    {
        'title': 'Patient Details',
        'id': 'patientDetails'
    },
    {
        'title': 'Admission Details',
        'id': 'admissionDetails'
    },
    {
        'title': 'Investigations',
        'id': 'investigations'
    }
];

export const WARDS = [
    "AMU",
    "AECU",
    "CCU",
    "CDU",
    "Coulsdon",
    "Dolphin Unit",
    "ED Majors",
    "ED Paediatrics",
    "ED Resus",
    "ED Subwait",
    "Edgecombe",
    "ESC Clinic",
    "ESC Recovery",
    "Fairfield 1",
    "Fairfield 2",
    "HDU",
    "Heathfield 1",
    "Heathfield 2",
    "Home",
    "Hope Ward",
    "ITU",
    "Kenley 1",
    "Kenley 2",
    "Mary Ward",
    "Purley 1",
    "Purley 2",
    "Purley 3",
    "Queens 1",
    "Queens ",
    "Queens 3",
    "Rupert Bear Ward",
    "SECU",
    "UCC",
    "Wandle 1",
    "Wandle 2",
    "Wandle 3",
    "Discharge Lounge",
];

export const PCS = [
    "Right iliac fossa (RIF) Abdominal pain",
    "Left iliac fossa (LIF) Abdominal pain",
    "Right upper quadrant (RUQ) Abdominal pain",
    "Left upper quadrant (LUQ) Abdominal pain",
    "Suprapubic  Abdominal pain",
    "Loin Abdominal pain",
    "Epigastric Abdominal pain",
    "Central Abdominal pain",
    "Generalised Abdominal pain",
    "Vomiting",
    "Diarrhoea",
    "Constipation",
    "Rectal pain",
    "Jaundice",
    "Rectal bleeding",
    "Abscess",
    "Head injury",
    "Trauma ",
    "Abdominal distension",
    "Tender hernia",
    "Irreducible hernia",
    "Dysphagia",
    "Limb ulcer",
    "Limb swelling",
    "Wound infection",
    "Urinary retention",
    "Haematuria",
    "Groin swelling",
    "Scrotal swelling",
    "Testicular pain",
    "Penile swelling",
    "Penile pain",
    "Fever",
    "Malaena",
    "Haematemesis",
    "Dysuria",
    "Penile discharge",
    "Reduced stoma output",
    "Faecal incontinence",
    "Heartburn",
    "Stomal prolapse",
    "Bleeding stoma",
    "Bleeding wound",
    "Breast swelling",
    "General malaise",
    "Post-op Thyroid complication",
    "Head injury on anticoagulation",
];

export const DIAGNOSES = [
    "Epigastric Hernia",
    "Umbilical Hernia",
    "Inguinal Hernia",
    "Ventral Hernia",
    "Spigelian Hernia",
    "Incisional Hernia",
    "Paraumbilical Hernia",
    "Femoral Hernia",
    "Lumbar Hernia",
    "Parastomal Hernia",
    "Internal Hernia",
    "Abscess",
    "Acute pancreatitis",
    "Acute urinary retention",
    "Addison's disease",
    "Adrenaloma",
    "Anal fistula",
    "Anastomotic leak",
    "Aortic aneurysm",
    "Aortic dissection",
    "Appendicitis",
    "Ascending cholangitis",
    "Benign Prostate Hypertrophy",
    "Bile leak",
    "Bladder cancer",
    "Bladder perforation",
    "Bowel ischaemia",
    "Bowel perforation",
    "Breast abscess",
    "Breast cancer",
    "Caecal volvulus",
    "Carcinoid tumour",
    "Carotid artery disease",
    "Cellulitis",
    "Cholangiocarcinoma",
    "Cholecystitis",
    "Choledocholithiasis",
    "Cholelithiasis",
    "Chronic pancreatitis",
    "Colitis",
    "Colon cancer",
    "Colonic stricture",
    "Critical limb ischaemia",
    "Crohn's disease",
    "Cystitis",
    "Deep vein thrombosis",
    "Diabetic foot ulcer",
    "Diverticular bleed",
    "Diverticulitis",
    "Diverticulosis",
    "Enteritis",
    "Enterocutaneous fistula",
    "Epidydimitis",
    "Epidydimo-orchitis",
    "Fournier's gangrene",
    "Gallbladder cancer",
    "Gastric outlet obstruction",
    "Gastric volvulus",
    "Gastritis",
    "Gastro-intestinal stromal tumour",
    "Gastro-oesophageal Reflux Disease",
    "Gastroenteritis",
    "Gastroparesis",
    "Goitre",
    "Grave's disease",
    "Haematoma",
    "Haemothorax",
    "Hashimoto's disease",
    "Hernia",
    "Hydronephrosis",
    "Hyperparathyroidism",
    "Hyperthyroidism",
    "Hypoparathyroidism",
    "Hypothyroidism",
    "Ileus",
    "Ingested foreign body",
    "Intra-abdominal collection",
    "Intracranial haemorrhage ",
    "Intussusception",
    "Large bowel obstruction",
    "Liver laceration",
    "Mastalgia",
    "Mastitis",
    "Mesenteric ischaemia",
    "Multiple Endocrine Neoplasia",
    "Necrotising fasciitis",
    "Oesophageal varices",
    "Pancreatic cancer",
    "Paraphimosis",
    "Pelvic floor dysfunction",
    "Penile cancer",
    "Perforated peptic ulcer",
    "Perianal abscess",
    "Peripheral aneursym",
    "Peripheral vascular disease",
    "Phimosis",
    "Pilonidal sinus",
    "Pneumothorax",
    "Prostate cancer",
    "Prostatitis",
    "Pseudo-obstruction",
    "Pulmonary embolism",
    "Pyelonephritis",
    "Rectal cancer",
    "Renal cancer",
    "Rib fracture",
    "Scrotal abscess",
    "Seroma",
    "Sigmoid volvulus",
    "Small bowel obstruction",
    "Splenic trauma",
    "Stoma complication",
    "Terminal ileitis",
    "Testicular cancer",
    "Testicular torsion",
    "Thrombophlebitis",
    "Thyroid cancer",
    "Thyroid nodule",
    "Toxic megacolon",
    "Trauma",
    "Ulcerative Colitis",
    "Ureteric injury",
    "Ureterolithiasis",
    "Urethral injury",
    "Urethral stricture",
    "Urinary incontinence",
    "Urinary tract infection",
    "Urosepsis",
    "Varicose veins",
    "Vasculitis",
    "Venous Insufficiency",
    "Wound infection",
    "Axillary Abscess",
    "Perianal Abscess",
    "Buttock Abscess",
    "Chest Abscess",
    "Back Abscess",
    "Scalp Abscess",
    "Abdominal Abscess",
    "Pilonidal Abscess",
    "Other Abscess",
    "Groin Abscess",
    "Scrotal Abscess",
    "Breast Abscess",
    "Abdominal wall Abscess",
    "Head and neck Abscess",
    "Liver Abscess",
];

export const CONSULTANTS = [
    "Anna Walsh",
    "George Mantides",
    "David Westbroek",
    "Eleni Anastasiadis ",
    "Paul Dent",
    "Alessandra Ferro",
    "Rhys Thomas",
    "Athanasios Argyropoulos",
    "Said Mohamed",
    "Charis Kyriakides",
    "Aditya Pareek",
    "Stephen Brennan",
    "Serena Sabato-Ceraldi",
    "Filip Frohlich",
    "Stella Vig",
    "Babbin John",
    "Damien Kelleher",
    "Muti Abulafi",
    "Jonathan Van Dellen",
    "Nasr Arsanious",
    "Samuel Osaghae",
    "Ian Swift",
    "Lubna Noor",
    "Mark Lynch",
    "Sanjay Joshi",
    "Sarah Horn",
    "Arun Shanmuganandan",
    "Wail Al Sarakbi",
    "Francesco DiMaggio",
];

export const CATEGORIES = [
    "1-New",
    "4-Hot clinic",
    "3-TBA",
    "2-Inpatients",
];

export const SPECIALTIES = [
    "Upper GI",
    "Colorectal",
    "Urology",
    "Vascular",
    "Endocrine-Breast",
    "Emergency",
];

export const SEXES = [
    "Male",
    "Female",
    "Other"
];

export const INVESTIGATIONS = [
    "Some investigations"
]